# Site settings
title: crowdrouter
email: mario.barrenechea@colorado.edu
description: > # this means to ignore newlines until "baseurl:"
  The crowdrouter is a hands-on programmer web framework for creating and maintaining 
  workflows and tasks to the crowd.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/project-epic/crowdrouter" # the base hostname & protocol for your site
twitter_username: mbarrenecheajr
github_username:  mbarrenecheajr

# Build settings
markdown: kramdown
